index:
  path: /
  controller: MaxServ\App\Controller\IndexController::index

products:
  path: /products
  controller: MaxServ\App\Controller\IndexController::products

product:
  path: /product/{sku}
  controller: MaxServ\App\Controller\IndexController::product
  requirements:
    sku: '[a-zA-Z0-9-]+'

retrieveApiProducts:
  path: /retrieve-api-products
  controller: MaxServ\App\Controller\IndexController::retrieveApiProducts

retrieveApiProductsAmount:
  path: /retrieve-api-products/{amount}
  controller: MaxServ\App\Controller\IndexController::retrieveApiProducts
  requirements:
    amount: '\d+'